---
- name: EXTRAS
  hosts: localhost
  tasks:
    - name: Install bash-completion, nano, net-tools, curl, yum-utils, centos-release-scl-rh
      yum:
        name: '{{ packages }}'
        state: present
      vars:
        packages:
          - nano
          - bash-completion
          - net-tools
          - curl
          - yum-utils
          - centos-release-scl-rh
