# yum -y update
# yum install epel-release
# yum --enablerepo=epel -y install ansible openssh-clients
---
- name: 'Config Rails Centos 7'
  hosts: localhost

# SYSTEM
- import_playbook: system.yml

# EPEL
- import_playbook: epel.yml

# EXTRAS
- import_playbook: extras.yml

# AJUSTES
- import_playbook: ajustes.yml

# VIM
- import_playbook: vim.yml

# GIT
- import_playbook: git.yml

# NGINX
- import_playbook: nginx.yml

# NODE|YARN
- import_playbook: nodeyarn.yml

# POSTGRES12
- import_playbook: postgres12.yml

# RVM
- import_playbook: rvm.yml