---
- hosts: localhost
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest

    - name: Enable service nginx
      service:
        name: nginx
        enabled: yes

    - name: Start nginx
      service:
        name: nginx
        state: started
