---
- name: NODE|YARN
  hosts: localhost
  tasks:
    - name: Nodejs12 prerequisites
      yum:
        name:
          - gcc-c++
          - make
        state: present

    - name: Nodejs12 download
      shell: curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
      args:
        warn: no

    - name: Nodejs12 install
      yum:
        name: nodejs
        state: present

    - name: Yarn download
      shell: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo -o /etc/yum.repos.d/yarn.repo
      args:
        warn: no

    - name: Yarn install
      yum:
        name: yarn
        state: present

    - name: Install mjml
      command: npm install -g mjml
