---
- hosts: localhost
  tasks:
    - name: Install vim
      yum:
        name: vim-enhanced
        state: latest
    
    - name: Config vimrc
      copy:
        src: ./vimrc
        dest: /etc/vimrc
