---
- name: VIM
  hosts: localhost
  tasks:
    - name: Install vim
      yum:
        name: vim-enhanced
        state: present

    - name: Config vimrc
      copy:
        src: ./vimrc
        dest: /etc/vimrc
